# MicroSD Card Adapter
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_CS = const(5)
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_SCK = const(6)
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_MOSI = const(7)
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_MISO = const(4)