# DHT22
GPIO_PIN_INPUT_DHT22 = const(2)

# BMP280
GPIO_PIN_I2C_BMP280_SDA = const(0)
GPIO_PIN_I2C_BMP280_SCL = const(1)

# MicroSD Card Adapter
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_CS = const(5)
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_SCK = const(6)
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_MOSI = const(7)
GPIO_PIN_SPI_MICROSD_CARD_ADAPTER_MISO = const(4)
